uploads = []

[[generated]]
id = "mI4Gb7Rt0gYn7T6-lA_z6"
uri = "file://attached_assets/generated_images/app-illustration.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dhhMDnTC17HzGWGoZVHd5"
uri = "file://attached_assets/generated_images/app-illustration-v2.png"
type = "image"
title = "grayscale schematic app screens"

[[outputs]]
id = "eZisqpFSQUy273E2RKLEQ"
uri = "file://attached_assets/stock_images/property_inspection_1.jpg"
type = "image"
title = "person using tablet in modern apartment, real estate inspection"

[[outputs]]
id = "J9ixqBg0GXD9Erf5AY-a0"
uri = "file://attached_assets/stock_images/property_inspection_2.jpg"
type = "image"
title = "person using tablet in modern apartment, real estate inspection"

[[outputs]]
id = "q0aTGMU7YPAir2GJZ5tE3"
uri = "file://attached_assets/stock_images/property_inspection_3.jpg"
type = "image"
title = "person using tablet in modern apartment, real estate inspection"
